[project]
name = "solar-backend"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.1",
    "djangorestframework>=3.18.1",
    "psycopg[binary]>=3.3.6",
    "python-dotenv>=1.2.4",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-django>=4.14.0",
    "ruff>=0.16.10",
]

[tool.pytest]
DJANGO_SETTINGS_MODULE = "config.settings"

[tool.ruff.lint]
extend-select = ["I", "B", "UP", "DJ"]
